/*
 * This file was automatically generated by EvoSuite
 */

package org.dom4j.swing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.ArrayList;
import org.dom4j.InvalidXPathException;
import org.dom4j.XPath;
import org.dom4j.dom.DOMDocumentType;
import org.dom4j.swing.XMLTableColumnDefinition;
import org.dom4j.tree.FlyweightAttribute;
import org.dom4j.xpath.DefaultXPath;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestXMLTableColumnDefinition {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition();
      xMLTableColumnDefinition0.handleException((Exception) null);
      assertEquals(0, xMLTableColumnDefinition0.getType());
  }

  @Test
  public void test1()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition("node", "node", 3);
      int int0 = xMLTableColumnDefinition0.getType();
      assertEquals(3, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition();
      xMLTableColumnDefinition0.setType(1909);
      assertEquals(1909, xMLTableColumnDefinition0.getType());
  }

  @Test
  public void test3()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition("node", "node", 3);
      DefaultXPath defaultXPath0 = (DefaultXPath)xMLTableColumnDefinition0.getXPath();
      assertNotNull(defaultXPath0);
      
      XMLTableColumnDefinition xMLTableColumnDefinition1 = new XMLTableColumnDefinition("node", (XPath) defaultXPath0, 3);
      assertEquals(3, xMLTableColumnDefinition0.getType());
      assertEquals(3, xMLTableColumnDefinition1.getType());
  }

  @Test
  public void test4()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition();
      xMLTableColumnDefinition0.setColumnNameXPath((XPath) null);
      assertNull(xMLTableColumnDefinition0.getName());
  }

  @Test
  public void test5()  throws Throwable  {
      DOMDocumentType dOMDocumentType0 = new DOMDocumentType("n", "n");
      DefaultXPath defaultXPath0 = (DefaultXPath)dOMDocumentType0.createXPath("n");
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition((XPath) defaultXPath0, (XPath) defaultXPath0, 1);
      Class<Object> class0 = xMLTableColumnDefinition0.getColumnClass();
      assertEquals("java.lang.String", class0.getName());
  }

  @Test
  public void test6()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition();
      XPath xPath0 = xMLTableColumnDefinition0.getColumnNameXPath();
      assertNull(xPath0);
  }

  @Test
  public void test7()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition();
      xMLTableColumnDefinition0.setXPath((XPath) null);
      assertNull(xMLTableColumnDefinition0.getName());
  }

  @Test
  public void test8()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition();
      String string0 = xMLTableColumnDefinition0.getName();
      assertNull(string0);
  }

  @Test
  public void test9()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition("node", "node", 3);
      xMLTableColumnDefinition0.setName("node");
      assertEquals(3, xMLTableColumnDefinition0.getType());
  }

  @Test
  public void test10()  throws Throwable  {
      int int0 = XMLTableColumnDefinition.parseType((String) null);
      assertEquals(0, int0);
  }

  @Test
  public void test11()  throws Throwable  {
      int int0 = XMLTableColumnDefinition.parseType("");
      assertEquals(0, int0);
  }

  @Test
  public void test12()  throws Throwable  {
      int int0 = XMLTableColumnDefinition.parseType("string");
      assertEquals(1, int0);
  }

  @Test
  public void test13()  throws Throwable  {
      int int0 = XMLTableColumnDefinition.parseType("no>de");
      assertEquals(0, int0);
  }

  @Test
  public void test14()  throws Throwable  {
      int int0 = XMLTableColumnDefinition.parseType("node");
      assertEquals(3, int0);
  }

  @Test
  public void test15()  throws Throwable  {
      DOMDocumentType dOMDocumentType0 = new DOMDocumentType("t|B", "t|B");
      DefaultXPath defaultXPath0 = (DefaultXPath)dOMDocumentType0.createXPath("t|B");
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition((XPath) defaultXPath0, (XPath) defaultXPath0, 2);
      Class<Object> class0 = xMLTableColumnDefinition0.getColumnClass();
      assertEquals(1025, class0.getModifiers());
  }

  @Test
  public void test16()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition("node", "node", 3);
      Class<Object> class0 = xMLTableColumnDefinition0.getColumnClass();
      assertEquals(true, class0.isInterface());
  }

  @Test
  public void test17()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition();
      Class<Object> class0 = xMLTableColumnDefinition0.getColumnClass();
      assertEquals("Object", class0.getSimpleName());
  }

  @Test
  public void test18()  throws Throwable  {
      DOMDocumentType dOMDocumentType0 = new DOMDocumentType("n", "n");
      DefaultXPath defaultXPath0 = (DefaultXPath)dOMDocumentType0.createXPath("n");
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition((XPath) defaultXPath0, (XPath) defaultXPath0, 1);
      FlyweightAttribute flyweightAttribute0 = new FlyweightAttribute("n", "n");
      String string0 = (String)xMLTableColumnDefinition0.getValue((Object) flyweightAttribute0);
      assertEquals("", string0);
      assertNotNull(string0);
      assertEquals(1, xMLTableColumnDefinition0.getType());
  }

  @Test
  public void test19()  throws Throwable  {
      DOMDocumentType dOMDocumentType0 = new DOMDocumentType("t|B", "t|B");
      DefaultXPath defaultXPath0 = (DefaultXPath)dOMDocumentType0.createXPath("t|B");
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition((XPath) defaultXPath0, (XPath) defaultXPath0, 2);
      FlyweightAttribute flyweightAttribute0 = new FlyweightAttribute("t|B", "t|B");
      ArrayList<?> arrayList0 = (ArrayList<?>)xMLTableColumnDefinition0.getValue((Object) flyweightAttribute0);
      assertEquals(Double.NaN, arrayList0);
      assertEquals(2, xMLTableColumnDefinition0.getType());
  }

  @Test
  public void test20()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition("node", "node", 3);
      String string0 = (String)xMLTableColumnDefinition0.getValue((Object) "");
      assertEquals(3, xMLTableColumnDefinition0.getType());
      assertNull(string0);
  }

  @Test
  public void test21()  throws Throwable  {
      XMLTableColumnDefinition xMLTableColumnDefinition0 = new XMLTableColumnDefinition();
      // Undeclared exception!
      try {
        xMLTableColumnDefinition0.getValue((Object) "3he");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
