/*
 * This file was automatically generated by EvoSuite
 */

package org.dom4j.swing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.dom4j.Document;
import org.dom4j.dom.DOMDocument;
import org.dom4j.swing.DocumentTreeModel;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDocumentTreeModel {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DOMDocument dOMDocument0 = new DOMDocument();
      DocumentTreeModel documentTreeModel0 = new DocumentTreeModel((Document) dOMDocument0);
      DOMDocument dOMDocument1 = (DOMDocument)documentTreeModel0.getDocument();
      assertEquals("", dOMDocument1.getText());
  }

  @Test
  public void test1()  throws Throwable  {
      DOMDocument dOMDocument0 = new DOMDocument("FMOyS\"83$3");
      DocumentTreeModel documentTreeModel0 = new DocumentTreeModel((Document) dOMDocument0);
      documentTreeModel0.setDocument((Document) dOMDocument0);
      assertNull(dOMDocument0.getXMLEncoding());
  }
}
