/*
 * This file was automatically generated by EvoSuite
 */

package org.dom4j.bean;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.dom4j.Element;
import org.dom4j.QName;
import org.dom4j.bean.BeanDocumentFactory;
import org.dom4j.bean.BeanElement;
import org.dom4j.tree.DefaultAttribute;
import org.junit.BeforeClass;
import org.xml.sax.Attributes;
import org.xml.sax.helpers.AttributesImpl;

@RunWith(EvoSuiteRunner.class)
public class TestBeanDocumentFactory {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      BeanDocumentFactory beanDocumentFactory0 = new BeanDocumentFactory();
      BeanElement beanElement0 = (BeanElement)beanDocumentFactory0.createElement("/text()", "/text()");
      assertEquals(false, beanElement0.isReadOnly());
  }

  @Test
  public void test1()  throws Throwable  {
      BeanDocumentFactory beanDocumentFactory0 = (BeanDocumentFactory)BeanDocumentFactory.getInstance();
      assertNotNull(beanDocumentFactory0);
  }

  @Test
  public void test2()  throws Throwable  {
      BeanDocumentFactory beanDocumentFactory0 = new BeanDocumentFactory();
      beanDocumentFactory0.handleException((Exception) null);
  }

  @Test
  public void test3()  throws Throwable  {
      BeanDocumentFactory beanDocumentFactory0 = new BeanDocumentFactory();
      QName qName0 = beanDocumentFactory0.createQName("#Vh", "#Vh", "#Vh");
      AttributesImpl attributesImpl0 = new AttributesImpl();
      BeanElement beanElement0 = (BeanElement)beanDocumentFactory0.createElement(qName0, (Attributes) attributesImpl0);
      DefaultAttribute defaultAttribute0 = (DefaultAttribute)beanDocumentFactory0.createAttribute((Element) beanElement0, "#Vh", "#Vh");
      assertEquals("", defaultAttribute0.getNamespaceURI());
  }
}
