/*
 * This file was automatically generated by EvoSuite
 */

package org.dom4j.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.dom4j.Element;
import org.dom4j.ElementHandler;
import org.dom4j.dom.DOMDocument;
import org.dom4j.dom.DOMDocumentType;
import org.dom4j.dom.DOMElement;
import org.dom4j.io.PruningElementStack;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestPruningElementStack {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[2];
      PruningElementStack pruningElementStack0 = new PruningElementStack(stringArray0, (ElementHandler) null);
      // Undeclared exception!
      try {
        pruningElementStack0.pathMatches((Element) null, (Element) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[4];
      PruningElementStack pruningElementStack0 = new PruningElementStack(stringArray0, (ElementHandler) null, 2524);
      assertNotNull(pruningElementStack0);
  }

  @Test
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[2];
      PruningElementStack pruningElementStack0 = new PruningElementStack(stringArray0, (ElementHandler) null);
      Element element0 = pruningElementStack0.popElement();
      assertNull(element0);
  }

  @Test
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[10];
      PruningElementStack pruningElementStack0 = new PruningElementStack(stringArray0, (ElementHandler) null);
      assertNotNull(pruningElementStack0);
      
      DOMDocumentType dOMDocumentType0 = new DOMDocumentType("", "");
      DOMDocument dOMDocument0 = new DOMDocument(dOMDocumentType0);
      DOMElement dOMElement0 = (DOMElement)dOMDocument0.addElement("", "");
      boolean boolean0 = pruningElementStack0.validElement((Element) dOMElement0, 6);
      assertEquals(false, boolean0);
  }

  @Test
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[11];
      stringArray0[1] = "";
      PruningElementStack pruningElementStack0 = new PruningElementStack(stringArray0, (ElementHandler) null);
      assertNotNull(pruningElementStack0);
      
      DOMDocumentType dOMDocumentType0 = new DOMDocumentType("", "");
      DOMDocument dOMDocument0 = new DOMDocument(dOMDocumentType0);
      DOMElement dOMElement0 = (DOMElement)dOMDocument0.addElement(":", ":");
      boolean boolean0 = pruningElementStack0.validElement((Element) dOMElement0, 1);
      assertEquals(true, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[1];
      PruningElementStack pruningElementStack0 = null;
      try {
        pruningElementStack0 = new PruningElementStack(stringArray0, (ElementHandler) null);
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * Invalid path of length: 1 it must be greater than 2
         */
      }
  }
}
