/*
 * This file was automatically generated by EvoSuite
 */

package org.dom4j.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.dom4j.DefaultDocumentFactory;
import org.dom4j.DocumentFactory;
import org.dom4j.ElementHandler;
import org.dom4j.io.DocumentResult;
import org.dom4j.io.SAXContentHandler;
import org.dom4j.tree.DefaultDocument;
import org.dom4j.tree.NamespaceStack;
import org.junit.BeforeClass;
import org.xml.sax.ContentHandler;
import org.xml.sax.ext.DefaultHandler2;
import org.xml.sax.ext.LexicalHandler;

@RunWith(EvoSuiteRunner.class)
public class TestDocumentResult {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DocumentResult documentResult0 = new DocumentResult();
      DefaultDocument defaultDocument0 = (DefaultDocument)documentResult0.getDocument();
      assertEquals("", defaultDocument0.getStringValue());
  }

  @Test
  public void test1()  throws Throwable  {
      DocumentResult documentResult0 = new DocumentResult();
      DefaultHandler2 defaultHandler2_0 = new DefaultHandler2();
      documentResult0.setHandler((ContentHandler) defaultHandler2_0);
      assertNull(documentResult0.getSystemId());
  }

  @Test
  public void test2()  throws Throwable  {
      SAXContentHandler sAXContentHandler0 = new SAXContentHandler();
      DocumentResult documentResult0 = new DocumentResult(sAXContentHandler0);
      documentResult0.setHandler((ContentHandler) sAXContentHandler0);
      assertEquals(false, sAXContentHandler0.isIncludeExternalDTDDeclarations());
  }

  @Test
  public void test3()  throws Throwable  {
      DocumentResult documentResult0 = new DocumentResult();
      DefaultHandler2 defaultHandler2_0 = new DefaultHandler2();
      documentResult0.setLexicalHandler((LexicalHandler) defaultHandler2_0);
      assertNull(documentResult0.getSystemId());
  }

  @Test
  public void test4()  throws Throwable  {
      DocumentResult documentResult0 = new DocumentResult();
      NamespaceStack namespaceStack0 = new NamespaceStack();
      DefaultDocumentFactory defaultDocumentFactory0 = (DefaultDocumentFactory)namespaceStack0.getDocumentFactory();
      SAXContentHandler sAXContentHandler0 = new SAXContentHandler((DocumentFactory) defaultDocumentFactory0, (ElementHandler) null);
      documentResult0.setLexicalHandler((LexicalHandler) sAXContentHandler0);
      assertEquals(false, sAXContentHandler0.isStripWhitespaceText());
  }
}
