/*
 * This file was automatically generated by EvoSuite
 */

package org.dom4j.tree;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.dom4j.Namespace;
import org.dom4j.tree.NamespaceCache;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestNamespaceCache {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      NamespaceCache namespaceCache0 = new NamespaceCache();
      Namespace namespace0 = namespaceCache0.createNamespace("g", "g");
      assertEquals(false, namespace0.supportsParent());
  }

  @Test
  public void test1()  throws Throwable  {
      NamespaceCache namespaceCache0 = new NamespaceCache();
      Namespace namespace0 = namespaceCache0.get("5$}n5ZN2eZN8sj)+#_", "5$}n5ZN2eZN8sj)+#_");
      assertEquals("xmlns:5$}n5ZN2eZN8sj)+#_=\"5$}n5ZN2eZN8sj)+#_\"", namespace0.asXML());
  }

  @Test
  public void test2()  throws Throwable  {
      NamespaceCache namespaceCache0 = new NamespaceCache();
      Namespace namespace0 = namespaceCache0.get("g");
      assertEquals("g", namespace0.getText());
  }
}
