/*
 * This file was automatically generated by EvoSuite
 */

package org.dom4j.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.dom4j.QName;
import org.dom4j.util.IndexedDocumentFactory;
import org.dom4j.util.IndexedElement;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestIndexedDocumentFactory {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      IndexedDocumentFactory indexedDocumentFactory0 = new IndexedDocumentFactory();
      QName qName0 = indexedDocumentFactory0.createQName("getBaseURI", "getBaseURI", "getBaseURI");
      IndexedElement indexedElement0 = (IndexedElement)indexedDocumentFactory0.createElement(qName0, 0);
      assertEquals("<getBaseURI:getBaseURI xmlns:getBaseURI=\"getBaseURI\"/>", indexedElement0.asXML());
  }

  @Test
  public void test1()  throws Throwable  {
      IndexedDocumentFactory indexedDocumentFactory0 = (IndexedDocumentFactory)IndexedDocumentFactory.getInstance();
      assertNotNull(indexedDocumentFactory0);
  }

  @Test
  public void test2()  throws Throwable  {
      IndexedDocumentFactory indexedDocumentFactory0 = new IndexedDocumentFactory();
      IndexedElement indexedElement0 = (IndexedElement)indexedDocumentFactory0.createElement("iIb", "iIb");
      assertEquals(0, indexedElement0.nodeCount());
  }
}
